# Generated by Django 4.2.16 on 2024-12-30 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedsRecognition', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupabaseUser',
        ),
    ]
