# Generated by Django 4.2.16 on 2025-01-11 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedsRecognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedMedication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255)),
                ('scan_date', models.DateTimeField(auto_now_add=True)),
                ('dosage', models.CharField(blank=True, max_length=255, null=True)),
                ('prescription_details', models.JSONField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_medications', to='MedsRecognition.profile')),
            ],
            options={
                'db_table': 'scanned_medication',
                'managed': True,
            },
        ),
    ]
