# Generated by Django 4.2.18 on 2025-01-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("MedsRecognition", "0003_scannedmedication_active_ingredients_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medication",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("scan_date", models.DateTimeField(auto_now_add=True)),
                ("active_ingredients", models.JSONField(blank=True, null=True)),
                ("scanned_text", models.TextField(blank=True, null=True)),
                ("dosage", models.CharField(blank=True, max_length=255, null=True)),
                ("prescription_details", models.JSONField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="MedsRecognition.profile",
                    ),
                ),
            ],
            options={
                "db_table": "medication",
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="ScannedMedication",
        ),
    ]
