"""Add image_url column to medications table

Revision ID: 6b14392afb55
Revises: 855a54151ecd
Create Date: 2025-02-24 22:01:31.528051

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b14392afb55"
down_revision: Union[str, None] = "855a54151ecd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "medications",
        sa.Column(
            "image_url",
            sa.String(length=2048),
            nullable=True,
            comment="URL of the uploaded medication image",
        ),
    )
    op.drop_index("idx_medications_profile_id", table_name="medications")
    op.drop_index("idx_medications_scan_date", table_name="medications")
    op.drop_index("idx_medications_title", table_name="medications")
    op.create_index("idx_medication_profile_id", "medications", ["profile_id"], unique=False)
    op.create_index("idx_medication_scan_date", "medications", ["scan_date"], unique=False)
    op.create_index("idx_medication_title", "medications", ["title"], unique=False)
    op.drop_index("idx_profiles_display_name", table_name="profiles")
    op.create_index("idx_profile_display_name", "profiles", ["display_name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_profile_display_name", table_name="profiles")
    op.create_index("idx_profiles_display_name", "profiles", ["display_name"], unique=False)
    op.drop_index("idx_medication_title", table_name="medications")
    op.drop_index("idx_medication_scan_date", table_name="medications")
    op.drop_index("idx_medication_profile_id", table_name="medications")
    op.create_index("idx_medications_title", "medications", ["title"], unique=False)
    op.create_index("idx_medications_scan_date", "medications", ["scan_date"], unique=False)
    op.create_index("idx_medications_profile_id", "medications", ["profile_id"], unique=False)
    op.drop_column("medications", "image_url")
    # ### end Alembic commands ###
