# Generated by Django 4.2.16 on 2025-01-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.UUIDField()),
                ("display_name", models.TextField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "profiles",
                "managed": True,
            },
        ),
        # # -- Add the FK constraint to auth.users --
        migrations.RunSQL(
            """
            ALTER TABLE public.profiles
            ADD CONSTRAINT profiles_user_id_fkey
            FOREIGN KEY (user_id)
            REFERENCES auth.users (id)
            ON DELETE CASCADE
            """,
            reverse_sql="""
                ALTER TABLE public.profiles
                DROP CONSTRAINT IF EXISTS profiles_user_id_fkey
                """,
        ),
        # -- Create the index for performance --
        migrations.RunSQL(
            """
            CREATE INDEX idx_profiles_user_id
            ON public.profiles (user_id)
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS idx_profiles_user_id
                """,
        ),
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("file_path", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "uploaded_images",
                "managed": True,
            },
        ),
    ]
